# Generated by Django 3.2.13 on 2022-06-28 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.BigIntegerField(blank=True, null=True)),
                ('dol_price', models.BigIntegerField(blank=True, null=True)),
                ('rub_price', models.BigIntegerField(blank=True, null=True)),
                ('delivery_time', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
